// AUTH ACTIONS
export const AUTH_USER = 'AUTH_USER',
  UNAUTH_USER = 'UNAUTH_USER',
  AUTH_ERROR = 'AUTH_ERROR',
  FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST',
  RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST',
  REGISTER_ERROR = 'REGISTER_ERROR',
  REGISTER_EMAIL_SENT = 'REGISTER_EMAIL_SENT',
  SET_NEW_TABLE_ID = 'SET_NEW_TABLE_ID',
  LOAD_BLANK_TABLE = 'LOAD_BLANK_TABLE',
  LOAD_SAVED_TABLE = 'LOAD_SAVED_TABLE',
  TOGGLE_LOAD_TABLE_MODAL = 'TOGGLE_LOAD_TABLE_MODAL',
  GET_USER_TABLE_DATA_SUCCESS = 'GET_USER_TABLE_DATA_SUCCESS',
  NOT_VERIFIED_LOGIN_ERROR = 'NOT_VERIFIED_LOGIN_ERROR';

// BBY API ACTIONS
export const POST_UPC = 'POST_UPC';

// TABLE ACTIONS
export const REMOVE_PRODUCT_FROM_TABLE = 'REMOVE_PRODUCT_FROM_TABLE',
  DECREMENT_PRODUCT_QUANTITY = 'DECREMENT_PRODUCT_QUANTITY',
  INCREMENT_PRODUCT_QUANTITY = 'INCREMENT_PRODUCT_QUANTITY',
  FORMAT_TABLE = 'FORMAT_TABLE',
  HIDE_ACTIONS = 'HIDE_ACTIONS',
  SHOW_ACTIONS = 'SHOW_ACTIONS',
  CLEAR_TABLE = 'CLEAR_TABLE',
  SYNCED_TABLE_TO_DB = 'SYNCED_TABLE_TO_DB',
  INVALID_UPC = 'INVALID_UPC';
