// AUTH ACTIONS
export const AUTH_USER = 'AUTH_USER',
  UNAUTH_USER = 'UNAUTH_USER',
  AUTH_ERROR = 'AUTH_ERROR',
  FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST',
  RESET_PASSWORD_REQUEST = 'REST_PASSWORD_REQUEST',
  PROTECTED_TEST = 'PROTECTED_TEST';

// BBY API ACTIONS
export const POST_UPC = 'POST_UPC',
  FORMAT_TABLE = 'FORMAT_TABLE';
