// AUTH ACTIONS
export const AUTH_USER = 'AUTH_USER',
  UNAUTH_USER = 'UNAUTH_USER',
  AUTH_ERROR = 'AUTH_ERROR',
  FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST',
  RESET_PASSWORD_REQUEST = 'REST_PASSWORD_REQUEST',
  PROTECTED_TEST = 'PROTECTED_TEST';

// USER PROFILE ACTION
export const FETCH_USER = 'FETCH_USER';
